### ISSUE TITLE
Anexo PDF no comentário não é clicável

### ISSUE THREAD

**Issue by jpmehl** [redelivre/delibera#100]
Ao testar a inserção de um anexo em PDF, percebe-se que ele não é clicável.  http://novocnpc.beta.redelivre.org.br/pauta/pauta-pra-mostrar-a-relatoria/#delibera-comment-104
![anexo-delibera](https://cloud.githubusercontent.com/assets/4163139/14270404/39f12fd6-fac4-11e5-9d16-47c611902c3c.png)

**Comment by jacsonp** [comment]
Está faltando a configuração do plugin comment attachment, a configuração se chama "Make attachment in comment a link?". Para acessar a configuração é em Configurações->Discussão ou pelo link /wp-admin/options-discussion.php

Segue Screen da opção:

![captura de tela de 2016-04-13 22 56 07](https://cloud.githubusercontent.com/assets/3977652/14514868/fd103d74-01ca-11e6-95d0-d57aa5d73776.png)
