### ISSUE TITLE
Concordar e discordar: não é possível trocar de opinião

### ISSUE THREAD

**Issue by jpmehl** [redelivre/delibera#102]
Quando clicamos em concordar ou discordar de uma pauta, o sistema não permite que a gente troque de opinião. Isto é fundamental, especialmente no caso de erro ao clicar. 
http://novocnpc.beta.redelivre.org.br/pauta/pauta-pra-mostrar-a-relatoria/#delibera-comment-106
![concordar-discordar-trocar-opiniao-delibera](https://cloud.githubusercontent.com/assets/4163139/14270469/ddbdcf66-fac4-11e5-9c4f-e044956a6e6c.png)

**Comment by lpirola** [comment]
ver junto a #116
