### ISSUE TITLE
Estilo botão (Editar) (Deletar)

### ISSUE THREAD

**Issue by jpmehl** [redelivre/delibera#104]
Os botões  (Editar) e (Deletar) estão sem estilo. 
![Uploading estilo-botos-editar-deletar-delibera.png…]()

**Comment by diegorojas** [comment]
@jpmehl localmente aqui não consigo cair numa tela com esses dois botões, não entendi direito ainda onde eles aparecem... :( Pode me mandar um link no beta onde eu deveria visualiza-los?

**Comment by jacsonp** [comment]
http://novocnpc.beta.redelivre.org.br/pauta/como-sera-o-processo-de-formacao-da-uso-para-os-conselheiros/ tem que estar logado

**Comment by jpmehl** [comment]
Eu vi que o estilo dos botões está melhor, mas o esquema para editar está bugado, acho que é coisa do DIV isto. @jacsonp fica nesta issue ou crio outra? 

![editar-proposta-delibera](https://cloud.githubusercontent.com/assets/4163139/14550206/1a5cb8a8-029d-11e6-94b9-06997ca270fd.png)

**Comment by jacsonp** [comment]
arrumei os botões @diegorojas

**Comment by diegorojas** [comment]
Deixei eles com o estilo padrão:

![editar-deletar](https://cloud.githubusercontent.com/assets/3632627/14863866/dc07fbd0-0c8d-11e6-82d4-a901eca917cc.png)

Vou fechar essa issue aqui e concentrar agora o resto da melhoria de toda o template de comentários na issue #90 ok?
