### ISSUE TITLE
Pauta em Validação: Melhorar estilo

### ISSUE THREAD

**Issue by jpmehl** [redelivre/delibera#107]
Na pauta em validação, tem muita inofrmação que não precisa, poderia ser apenas a Foto do usuário e o voto dele embaixo e o tempo que ele foi feito. 
O botão "de sua opinião" alem de não funcionar, não tem utilidade nesta fase.

![aprovacao-pauta](https://cloud.githubusercontent.com/assets/4163139/14291895/ee37c3a2-fb3b-11e5-8336-8887d2b52b1f.png)

**Comment by lpirola** [comment]
@diegorojas essa também tá precisando de uma melhoradinha!

**Comment by diegorojas** [comment]
Esse aqui vou direto no css. 

Mas to achando um excesso de "Dê sua opinião". Num poderia ser somente uma linha abaixo de tudo com isso aqui abaixo?
![login](https://cloud.githubusercontent.com/assets/3632627/14298299/a2610abe-fb5a-11e5-8f08-c4d84bd2b925.png)

**Comment by lpirola** [comment]
@jpmehl pode ajudar nessa?

**Comment by jpmehl** [comment]
Como eu disse no comentário acima, NÃO tem que ter o botão  "de sua opinão"

O resultado deve ser muito simples, o mais enxuto possível para uma rápida visualização: 

**Foto do usuário - Voto(sim ou não) - tempo de envio**

**Comment by diegorojas** [comment]
@jpmehl da uma olhada aqui na proposta que fiz, publiquei no beta

**Comment by diegorojas** [comment]
http://novocnpc.beta.redelivre.org.br/pauta/pauta-em-validacao-sobre-como-sera-o-processo-de-formacao-2/

**Comment by jpmehl** [comment]
Só não faz sentido as pessoas avaliarem a validação do outro, como tinha colocado acima. Só deve ter acima de tudo a possibilidade dele aprovar e reprovar a proposta e abaixo os box de quem já validou. Só fiquei na dúvida se a gente apresenta qual foi o voto de cada um. a princípio vamos mostar como cada um votou, se para a provar ou reprovar.

**Comment by diegorojas** [comment]
Retirando via css da classe .delibera_lista_validacoes. Isso: 

![avaliacao-da-validacao-de-outro](https://cloud.githubusercontent.com/assets/3632627/14678045/934c70cc-06ea-11e6-905c-82c6b8b1f177.png)
Viirando isso:
![sem-avaliacao](https://cloud.githubusercontent.com/assets/3632627/14678075/af30a77c-06ea-11e6-80b8-27361f2decaa.png)

Acho que agora matou pelo menos no desktop o basico

**Comment by jpmehl** [comment]
Está ótimo @diegorojas , no entanto, veja que os resultados estão caindo por cima do rodapé. Só precisa corrigir isto. 

![pauta-validacao-quebrando](https://cloud.githubusercontent.com/assets/4163139/14719120/d6cbdf2c-07d0-11e6-88da-0c2cf0b3ce37.png)

**Comment by diegorojas** [comment]
Da uma olhada se resolveu depois JP, e já fecha essa issue por favor?

**Comment by jpmehl** [comment]
Tá quase 100%, mas ainda no celular tá encavalando informaçòes. Acho que da pra retirar a informação sobre o tempo que o usuário validou, o "há 2 dias"...
![validacao-pauta](https://cloud.githubusercontent.com/assets/4163139/14872678/ef5808ba-0cc4-11e6-990d-9ea60415ed81.png)

**Comment by diegorojas** [comment]
Isso ai de mobile eu já ia fazer junto com a issue #109, mas beleza tirar o dia se for necessario
