### ISSUE TITLE
Bug: mudança de fase debate-relatoria

### ISSUE THREAD

**Issue by jpmehl** [redelivre/delibera#110]
Na pauta http://novocnpc.beta.redelivre.org.br/pauta/o-futuro-do-delibera-para-onde-vamos/ deveria ter mudado ontem pra relatoria, mas segue como "em discussão", no entanto, ao tentar fazer um comentário, ele não aparece a opção "proposta de encaminhamento" ou "opinião".

**Comment by jpmehl** [comment]
Avaliando outras pautas, percebi que a possibilidade de "opinião" x "proposta de encaminhamento" não está mais aparecendo nem quando a pauta está em discussão ainda.

**Comment by jacsonp** [comment]
mesmo que #135
