### ISSUE TITLE
Modulo pauta no front-end Delibera no DIVI

### ISSUE THREAD

**Issue by jpmehl** [redelivre/delibera#114]
Este módulo do Delibera deve possibilitar a seguinte configuração: 

1 - Definir quais campos serão apresentados;
1.1 - Título
1.2 - Conteúdo
1.3 - Tema
1.4 - Palavras Chave(sub-temas)

2 - Selecionar para qual tema a pauta do Front-end vai encaminhar;

**Comment by lpirola** [comment]
Essa solução deve ser criada dentro do plugin do delibera afim de aproveitar o ecosistema do tema genérico e respeitando os estilo do tema escolhido pelo usuário no wordpress.

**Comment by jpmehl** [comment]
Relato conforme nossa reunião @samueldu 
1. Ainda está bugado, não consigo criar pautas facilmente; 
2. Precisa melhorar o estilo conforme telas apresentadas; 
3. Permitir que a partir das sub-categorias da categoria escolhida para determinado formulário de criação de pautas no front, devem aparecer as sub-categorias para uma selecão através de check-box; 
4. Ao tentar criar uma pauta, o usuário que ainda não estiver logado deve ser levado para a área de cadastro, e após o cadastro efetuado deve voltar para o mesmo lugar;
5. Após concluir a inserção de uma proposta, o usuário deve ser direcionado para a página desta mesma proposta;

**Comment by jpmehl** [comment]
Aqui uma das coisas importantes que não está rolando é: Após concluir a inserção de uma proposta, o usuário deve ser direcionado para a página desta mesma proposta;
