### ISSUE TITLE
Módulo pautas delibera no DIV

### ISSUE THREAD

**Issue by jpmehl** [redelivre/delibera#115]
O módulo do Delibera no DIV que apresenta as pautas, podendo escolher quais temas são apresentados. 
No entanto, precisamos melhorar o estilo, pois ainda está muito duro. 
Outra demanda será a de colocar a possibilidade de concordar e discordar diretamente no front-end e já ter o botão de comentar no proprio módulo. para o qual vou abrir uma nova issue.

**Comment by jacsonp** [comment]
Código atual está aqui:
https://github.com/campanhacompleta/divi-child

**Comment by jacsonp** [comment]
delibera/themes/generic/form-nova-pauta.php

**Comment by jpmehl** [comment]
Aqui segue uma tela comentada de alguns erros e campos que não fazem sentido. 

![delibera-modulo-div](https://cloud.githubusercontent.com/assets/4163139/14749799/ed392fae-0897-11e6-9875-5fc63c32739b.png)

**Comment by jpmehl** [comment]
Só para documentar as conversas que tivemos @samueldu 

Implementar estilo  tanto para as propostas em "caixas" em destaque(com foto) como para as internas, que devem conter a)possibilidade de concordar b)possibilidade de discordar c) possibilidade de comentar d)botão que leve para a página interna da proposta.
Quando o usuário não estiver logado, ele poderá visualizar tudo, no entanto, ao clicar em qualquer possibilidade de interação ele deve ser levado para a área de login e após estar logado deverá voltar para a tela onde estava originalmente;
Na página interna de determinada categoria, devem apresentar todas as propostas daquela categoria, sendo que deve haver uma paginação/scroll infinito, isto é, quando houverem muitas propostas, devem ir aparecendo na medida que o usuário utiliza o scroll. A proposta é que se utilize Query Post Type Pauta; 
É preciso limpar a tela do módulo no Div de modo que fique fácil do usuário configurar;
É preciso estender o tema Generic para que ele possa ter uma sidebar; 
É preciso organizar a utilização de categorias e sub-categorias, de modo que possamos utilizá-las facilmente na criação de pautas no front;
