### ISSUE TITLE
Pauta aparece 4 vezes na tela

### ISSUE THREAD

**Issue by thalitasejanes** [redelivre/delibera#133]
![tela-pauta](https://cloud.githubusercontent.com/assets/4115304/18203694/e9b6cea8-70ee-11e6-9213-4d1886bfe6be.png)

**Comment by lpirola** [comment]
@thalitasejanes acreditamos que isso possa ter sido um problema no momento de cadastro. Consegue se lembrar de alguma ação especial no cadastro dessa pauta?

Todas as vezes que você cadastra, que esse problema acontece?
