### ISSUE TITLE
Sobre roadmap e versionamento

### ISSUE THREAD

**Issue by vgeorge** [redelivre/delibera#154]
Oi pessoal,

Faço parte da equipe de desenvolvimento do portal da comunidade do Mapas Culturais e queremos integrar o Delibera nele. Percebi que o desenvolvimento neste repositório está bastante ativo e gostaríamos de integrar nosso fluxo de trabalho aqui, se possível, ao invés de fazer um fork.

Neste momento gostaríamos de ter uma idéia geral do roadmap do projeto e sugerir o uso de versionamento para ajudar a construir uma versão estável do plugin. 

Abraços,
Vitor

**Comment by jacsonp** [comment]
@vgeorge Ola Vitor, estamos no momento com 3 atividades mais fortes nos delibera:
1) Integração com o plugin grupos (em fase de testes)
2) Compatibilidade com a versão 4.7.x do wordpress (90% concluída, ainda com algumas funções deprecated)
3) Integração de ferramentas para criação de "consultas públicas), possibilitando por exemplo um tipo novo da etapa de discussão, onde as interações são por paragrafo e um tipo novo de votação usando pairwase. Queremos também possibilitar a criação de questionários simples. Esse desenvolvimento está previsto para final de maio

Algumas issues estão sendo corrigidas no master que é para ser a versão estável do delibera, testada contra o wordpress 4.4.x, versão atual do wordpress na plataforma redelivre (http://redelivre.org.br), a qual estamos migrando na próxima semana para a versão 4.7.x, por isso que estamos fazendo correções
Temos ainda esforços de UX (https://github.com/redelivre/MutiraoUX/issues), é geral da redelivre, mas tem bastante coisa específica sobre o delibera

Nosso roadmap atual é:
Abr/Maio:
Grupos;
WP 4.7.x;
Consultas Públicas;

Sem data ainda:
UX, especialmente do painel;
Documentação (migrar de http://escoladedebate.cnpc.cultura.gov.br/ quando pronto);
Opções para customização de aparencia do tema padrão (genérico)

**Comment by vgeorge** [comment]
Obrigado pelos esclarecimentos, @jacsonp.
