### ISSUE TITLE
Preciso de um layout para a tela de votação para quando houve relatoria

### ISSUE THREAD

**Issue by jacsonp** [redelivre/delibera#160]
Gostaria de uma proposta de layout para a tela de votação para quando há relatoria de tempos propostas com base em outras, ao clicar no botão de ver a proposta completa fica com uma lista simples das propostas que serviram como base para a nova proposta sugerida pelo relator.
![image](https://cloud.githubusercontent.com/assets/3977652/25830671/c518d708-3434-11e7-95ab-8a1086b1f64b.png)

**Comment by thalitasejanes** [comment]
Pensei nas propostas serem mostradas após clicar, o que acham?

![fechado](https://cloud.githubusercontent.com/assets/4115304/26071237/c97cd10c-397d-11e7-9e84-035a1d8d5579.jpg)

![aberto](https://cloud.githubusercontent.com/assets/4115304/26071245/d1214690-397d-11e7-8dd8-b881ab931450.jpg)

**Comment by jacsonp** [comment]
Eu gostei, implemento assim, mas algum feedback, @diegorojas @jpmehl ?

**Comment by jacsonp** [comment]
@jacsonp Vai ficar assim, não vale dizer que está ruim depois, do-lhe 1
