### ISSUE TITLE
Melhorar parte da tela de resultados para validações

### ISSUE THREAD

**Issue by jacsonp** [redelivre/delibera#162]
Um das demandas de consultas públicas é validações de documento, reuniões e afins, para isso o delibera suporta colocar 2 etapas, Proposta de pauta e resultado, porém o layout do resultado após a validação está ficando a desejar como no exemplo:
![image](https://cloud.githubusercontent.com/assets/3977652/25931924/b441270c-35e5-11e7-8084-3d59ae5d58ee.png)

**Comment by thalitasejanes** [comment]
O que vocês consideram que precisa melhorar nesta tela? Não está claro o que temos que melhorar.

**Comment by jacsonp** [comment]
Na verdade acho meio simples demais, e até feito, poderia ter sem 3 colunas (um para cada tipo de validação), ou até mesmo em duas como era o projeto inicial, uma para o tipo e a outra para o resultado. Eu sou programador, mas até penso em gráfico de pizza, colocar numero de participantes vs numero de cadastrados, coisas do tipo, não é só desenho, UX mesmo

**Comment by thalitasejanes** [comment]
Eu sugiro o uso do negrito nos títulos (validação, rejeição, abstenção) e nos números de votos.

**Comment by jacsonp** [comment]
fixed at c6ece49
