### ISSUE TITLE
Sem paginação no tema padrão

### ISSUE THREAD

**Issue by jacsonp** [redelivre/delibera#164]
Não estamos vendo a paginação no tema padrão, ela está escondida devido a falta de CSS, precisamos arrumar isso urgentemente
http://escoladedebate.cnpc.cultura.gov.br/pauta/
http://cnpc.cultura.gov.br/pauta/

![image](https://cloud.githubusercontent.com/assets/3977652/26157032/7a9424ec-3aee-11e7-842e-c1dbe9cc46da.png)
Removendo o display:none para ver a paginação:
![image](https://cloud.githubusercontent.com/assets/3977652/26157079/9e4ed120-3aee-11e7-8848-8dda0e7c8fd1.png)

**Comment by jacsonp** [comment]
Sério gente, nada aqui? é uma paginação somente: versão programador, e vai ficar assim se nínguem falar nada:
![image](https://cloud.githubusercontent.com/assets/3977652/26565352/dde65296-44c0-11e7-8bcd-55c22aaefac5.png)
o "azul" mais escuto é o :hover
![image](https://cloud.githubusercontent.com/assets/3977652/26566071/ab16077a-44c6-11e7-90cd-64c57d82a44f.png)

**Comment by thalitasejanes** [comment]
Jac, veja se é isto aqui, as cores foram mantidas, o cinza é o #ebebeb
![delibera-pag](https://user-images.githubusercontent.com/4115304/26896863-ba18b2cc-4b9c-11e7-8e72-e76c874489ba.jpg)
