### ISSUE TITLE
Delibera side comment - proposta de desenho para aplicação de estilo

### ISSUE THREAD

**Issue by thalitasejanes** [redelivre/delibera#165]
A proposta é que a caixa se alinhe com o estilo do delibera.

Coloquei os comentários e a caixa de comentar junto, mas primeiro aparece os comentários e o botão comentar, apenas no clique aparece a caixa, conforme o sistema funciona atualmente.

o ícone escolhido para o botao 'deixe seu comentário' faz parte do pacote do delibera

 ![deliberacoment](https://cloud.githubusercontent.com/assets/4115304/26514089/f04dccb6-4245-11e7-8237-3ac118cb2d21.jpg)

**Comment by jacsonp** [comment]
Legal, estou publicando a possibilidade de anexo e mais algumas correções de funcionamento hoje, tem que prever reposta a comentário também (botão, posição do texto, etc)

**Comment by thalitasejanes** [comment]
Detalhes pedidos
![deliberacoment](https://cloud.githubusercontent.com/assets/4115304/26698167/3a1293aa-46eb-11e7-92c2-25c5ea5c5cae.jpg)
