### ISSUE TITLE
Anexar documentos relevantes nos comentários

### ISSUE THREAD

**Issue by lpirola** [redelivre/delibera#18]

**Comment by lpirola** [comment]
inserir dentro do plugin do delibera o plugin "wpcomments-upload" e documentar o uso.

**Comment by lpirola** [comment]
https://github.com/wp-plugins/easy-comment-uploads

**Comment by jacsonp** [comment]
Estava olhando, o pessoal do MJ colocou um esquema para subir pdf, será que não é aproveitar e mudar para outros documentos, colocar em comentários e preferencialmente fazer as checagem de segurança padrão do WP e ver se está na lista de permitidos, caso não esteja sendo feita.

**Comment by lpirola** [comment]
Qual o repo que ele utilizam?

**Comment by jacsonp** [comment]
já está no delibera principal, veio por pull request, olhei agora, está apenas no admin :(

**Comment by lpirola** [comment]
https://wordpress.org/plugins/comment-attachment/

**Comment by lpirola** [comment]
Eu deixei o plugin para comentário como obrigatório mas ao instalá-lo é possível desabilitar a possibilidade de fazer upload mesmo o plugin estando habilitado. O q acham?

**Comment by lpirola** [comment]
#51 Imagens representativas de como ficam as telas para adicionar anexos.

Input no frontend do tema:

<img width="1128" alt="screen shot 2016-02-19 at 10 12 37 am" src="https://cloud.githubusercontent.com/assets/14948/13175470/bebe9902-d6f1-11e5-9574-95fe5802906f.png">

Opções para anexar arquivos que está disponível em "Menu -> Configurações -> Discussão"

<img width="661" alt="screen shot 2016-02-19 at 10 13 36 am" src="https://cloud.githubusercontent.com/assets/14948/13175471/bec0a58a-d6f1-11e5-8b0e-7ace3f9e7305.png">
