### ISSUE TITLE
Notificação por e-mail

### ISSUE THREAD

**Issue by jacsonp** [redelivre/delibera#24]
_From @jpmehl on April 15, 2013 19:43_

As notificações por e-mail já estão funcionando, no entanto, é preciso permitir um editor de Html para que a configuração do e-mail possa ser melhor qualificada.

_Copied from original issue: ethymos/delibera#1_

**Comment by jacsonp** [comment]
_From @rodrigoprimo on May 2, 2013 17:45_

O Jacson já está mexendo nisso?

Temos um plugin, custom_email_notices, que faz justamente isso. Se quiserem podemos implementar.

**Comment by jacsonp** [comment]
_From @jpmehl on May 2, 2013 18:34_

Já tem implementação de notificação por email, só precisa de refino. O que
a gente quer é a possibilidade de um editor HTML pra mensagem de
notificação ficar mais bonitona.
Mas o avanço disto, que é o resposta por email, que é importante
desenvolvermos, visto que facilitará a dinâmica do debate pois as respostas
seriam computadas no sistema.
Fico a disposição para marcaram os um papo a respeito.
Abc
Em 02/05/2013 14:45, "Rodrigo Primo" notifications@github.com escreveu:

**Comment by cabelotaina** [comment]
Ola só retomando aqui @jpmehl :

> Já tem implementação de notificação por email, só precisa de refino. O que
> a gente quer é a possibilidade de um editor HTML pra mensagem de
> notificação ficar mais bonitona.

Já temos isso.

> Mas o avanço disto, que é o resposta por email, que é importante
> desenvolvermos, visto que facilitará a dinâmica do debate pois as respostas
> seriam computadas no sistema.

nesse caso esta issue poderia ser fechada ficamos apenas com a issue #14 e fazemos uma ref para ela...

**Comment by jpmehl** [comment]
Não sei se já resolveram, mas segue rolando notificação duplicada. 
![emails-duplicados-delibera](https://cloud.githubusercontent.com/assets/4163139/14292538/e958f380-fb3e-11e5-9ede-3312393a19e4.png)

**Comment by jpmehl** [comment]
Reforçando a importância de se resolver esta issue, a Loa acabou de criar 3 pautas, sendo que a notificação vem certinho, mas não tem qualquer linque que convide o usuário a acessar a pauta, conforme podem ver em anexo. 

![notificacacao-sem-linques](https://cloud.githubusercontent.com/assets/4163139/14386649/174a0100-fd7c-11e5-8cd5-64f3e06d0fe8.png)

**Comment by jacsonp** [comment]
Foi resolvido em partes, ainda precisamos resolver o problema do cabeçalho e rodapé padrão quando a configuração foi feita antes da correção que remove as palavras e deixa em branco.
![image](https://cloud.githubusercontent.com/assets/3977652/26160242/18e5c9d6-3af7-11e7-99a9-9b595d294969.png)
