### ISSUE TITLE
Autenticação Open ID

### ISSUE THREAD

**Issue by jacsonp** [redelivre/delibera#33]
_From @jpmehl on April 15, 2013 20:8_

Aqui entramos em um debate mais amplo, das redes federadas. Nossa proposta é permitir que se aproveitem os usuários de outras plataformas para facilitar o cadastro e a integração entre diferentes redes.

_Copied from original issue: ethymos/delibera#11_

**Comment by jacsonp** [comment]
_From @philltrindade on June 12, 2013 19:39_

Acredito que aqui cabe pontuar uma sugestão complementar: permitir (apesar de por padrão ficar desabilitado) login via Facebook. Não seria o caso de priorizar e nem depender da plataforma proprietária, mas de ter como mais uma opção (uma que, quanto mais abrangente o público do site, mais será relevante, creio eu).

**Comment by jacsonp** [comment]
_From @leogermani on June 12, 2013 20:51_

Eu acho que a parte de registro está fora do escopo do Delibera.

O Delibera é um plugin para o WordPress, e existem vários outros plugins de registro que permitem integração com diferentes redes, inclusive facebook, twitter e openID. 

Se eu já tenho um site que roda com um deles.. não quero que isso conflite com o Delibera. Ou se quiser fazer essa integração, posso usar um plugin dedicado a isso.

**Comment by jacsonp** [comment]
_From @jpmehl on June 12, 2013 21:34_

Salve Leo,

Acho que a linha é esta, mas cabe uma consideração: o delibera original
comporta diferentes níveis de permissão pra usuário: administrador,
coordenador e usuário comum. Acredito que seja importante vincularmos isto
as permissões nativas do WP, considerando também que temos uma pequena
distorção nas nomenclaturas.
Ainda sobre permissões, talvez valha um debate sobre elas, se são estas
mesmo ou se existem alterações a serem feitas.
Voltando sobre a questão apresentada pelo PHill e sua sugestão, para nos
isto é bem importante, considerando que estamos lançando alguns projetos
que utilizam o delibera no campanha e a questão do registro não esta bem
resolvida, precisamos de uma solução mesmo.
Se puder dar esta forca seria ótimo.
Abc

João Paulo Mehl
Ethymos soluções em web
(41) 3077-4163 / tim 96275518 / vivo 92211909
Em 12/06/2013 17:52, "leogermani" notifications@github.com escreveu:

**Comment by jacsonp** [comment]
_From @jpmehl on June 13, 2013 21:33_

Leo,

na realidade acho que a gente nem precisa criar nada novo, apenas habilitar
que o usuário novo que se cadastra no site que vai utilizar o delibera,
seja criado com permissões para fazer comentário, o que não ocorre hoje.

Quando um usuário se cadastra no delibera: ex
http://conferencialivrecuritiba.campanhacompleta.com.br/, ele consegue
fazer o cadastro direitinho, mas acaba não aparecendo pra mim que sou admin
como um usuário ativo. aparentemente ele fica com uma permissão "assinante"
e não da permissão para comentar no Delibera.

Para além disto, o fluxo do cadastro está ruim, pois faz o cadastro, mas
depois de homologado não leva pra página de destino do qual ele se
cadastrou, o ideal é que leve diretamente para a página de debate para que
possa começar a participar.

Podemos contar com vocês nesta? Estamos lançando a Conferência Livre de
Cultura de Curitiba e isto é muito estratégico para nossa ação junto ao
Ministério da Cultura e outras frentes de financiamento que estamos
fazendo. Além de ser a base para lançarmos outras conferências pelo Brasil.

Abraçao

Em 12 de junho de 2013 18:34, João Paulo Mehl jpmehl@ethymos.com.brescreveu:

> Salve Leo,
> 
> Acho que a linha é esta, mas cabe uma consideração: o delibera original
> comporta diferentes níveis de permissão pra usuário: administrador,
> coordenador e usuário comum. Acredito que seja importante vincularmos isto
> as permissões nativas do WP, considerando também que temos uma pequena
> distorção nas nomenclaturas.
> Ainda sobre permissões, talvez valha um debate sobre elas, se são estas
> mesmo ou se existem alterações a serem feitas.
> Voltando sobre a questão apresentada pelo PHill e sua sugestão, para nos
> isto é bem importante, considerando que estamos lançando alguns projetos
> que utilizam o delibera no campanha e a questão do registro não esta bem
> resolvida, precisamos de uma solução mesmo.
> Se puder dar esta forca seria ótimo.
> Abc
> 
> João Paulo Mehl
> Ethymos soluções em web
> (41) 3077-4163 / tim 96275518 / vivo 92211909
> Em 12/06/2013 17:52, "leogermani" notifications@github.com escreveu:
> 
> Eu acho que a parte de registro está fora do escopo do Delibera.
> 
> > O Delibera é um plugin para o WordPress, e existem vários outros plugins
> > de registro que permitem integração com diferentes redes, inclusive
> > facebook, twitter e openID.
> > 
> > Se eu já tenho um site que roda com um deles.. não quero que isso
> > conflite com o Delibera. Ou se quiser fazer essa integração, posso usar um
> > plugin dedicado a isso.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/ethymos/delibera/issues/11#issuecomment-19354626
> > .

## 

João Paulo Mehl
Ethymos Soluções em Web
www.ethymos.com.br
(41)3077-4163 / 9627-5518

**Comment by jacsonp** [comment]
Concordo com o Leo, esse não é o papel do plugin e sim da plataforma, embora ele implemente algumas funcionalidades fora do seu escopo, mas com objetivo de fluxo. Acredito que com a instalação do plugin https://github.com/redelivre/wp-opauth esse problema seja resolvido, não precisando que o delibera faça o papel, o que você @jpmehl podemos fechar esse aqui?

**Comment by jpmehl** [comment]
@jacsonp vamos fechar este pauta aqui que não faz sentido.

**Comment by jacsonp** [comment]
resolvido com uso do wp-openid e wp-opauth
