### ISSUE TITLE
Exibir histórico da pauta na fase de votação

### ISSUE THREAD

**Issue by jacsonp** [redelivre/delibera#38]
_From @rodrigoprimo on June 26, 2013 12:53_

_Copied from original issue: ethymos/delibera#24_

**Comment by jacsonp** [comment]
_From @jpmehl on March 26, 2015 22:50_

Acredito que isto tem relação com a Timeline. O que acha @jacsonp ?

**Comment by jpmehl** [comment]
@jacsonp tenho impressão que já tá resolvido isto.

**Comment by Andreqlp** [comment]
pode fechar?

**Comment by jacsonp** [comment]
Não, não é exibido os históricos da pauta para os usuários, e isso é
importante, so vê o histórico quem pede a impressão da pauta, o que eu
Imagina o seja tão claro

Em 18 de abr de 2017 6:54 PM, "André Quintino Lopes" <
notifications@github.com> escreveu:

**Comment by jacsonp** [comment]
a issue #122 resolve essa.
