### ISSUE TITLE
Melhorias na interface de relatoria

### ISSUE THREAD

**Issue by jacsonp** [redelivre/delibera#39]
_From @rodrigoprimo on June 26, 2013 12:54_

Estamos pensando em fazer algumas melhorias na tela de relatoria de uma pauta. Gostaríamos de ter uma maneira de mudar o status dos encaminhamentos que foram usados pelo relator para criar um terceiro. Talvez a gente não esteja entendendo alguma, mas achamos estranho os encaminhamentos usados como base para um outro irem também para a votação. Achávamos que apenas o encaminhamento criado pelo relator que iria para votação e os outros ficariam acessíveis apenas para manter o histórico. Além disso, pensamos em mudar uma pouco a interface para facilitar o processo de escolha do relator de quais encaminhamentos devem ir para votação. O Anderson está trabalhando numa tela e em breve devemos ter alguma coisa para apresentar.

_Copied from original issue: ethymos/delibera#25_

**Comment by jacsonp** [comment]
_From @jpmehl on March 26, 2015 22:48_

@rodrigoprimo você lembra se avançaram nisto? É uma demanda prioritária e pretendemos colocar na pauta no próximo período.

**Comment by jacsonp** [comment]
_From @rodrigoprimo on March 27, 2015 14:39_

Não lembro.

**Comment by jpmehl** [comment]
@lpirola @jacsonp era sobre o que estavamos conversando, da pra juntar com a outra pauta que fala sobre isto.

**Comment by lpirola** [comment]
#93 ?

**Comment by jacsonp** [comment]
o 4993df84f30919de71f2bfa0b7be403be958b4df corrigi dando a opção de ter ou não as propostas bases no momento da votação.
