### ISSUE TITLE
Depurar e reparar temas do delibera

### ISSUE THREAD

**Issue by jacsonp** [redelivre/delibera#4]
No delibera existe um sistema interno para facilitar a publicação que suporta temas, esse sistema tem 2 temas prontos hoje: Atena e Creta
    Ambos os sistemas pecam em bugs de apresentação, como falhas no responsivo, (larguras fixas ao invés de proporções). A ideia é documentar as issues e tentar reparar estilo e  falhas simples.

**Comment by rosanaw** [comment]
Desafio 9:

Tema Creta:

Página Inicial
- Alinhar menu e botões laterais deixando opções mais claras para o usuário
- Melhorar esquema de cores, diferenciar e padronizar botões por tipo de ação (votar, criar nova pauta, como participar)
- Largura das duas colunas não está ajustada nas resoluções abaixo de 800px
- Adicionar botão para voltar à página de discussões como no Atenas
- Filtro de pautas está com bullet da lista
- Sugestão de utilização do grid para ajuste do responsivo e melhor alinhamento dos elementos
- Sugestão de ajuste do filtro para que não precise clicar no botão recarregar a cada filtragem

Página da Pauta
- Resoluções abaixo de 910px estão com elementos colados nas laterais da tela
- Elementos da discussão estão centralizados (sugestão de colocar na lateral para melhor alinhamento visual, centralizar apenas em menores resoluções)
- Botões ao serem clicados estão com duas cores
- Cores do prazo da pauta de acordo com a data (exemplo: Encerra em ... dias: laranja. Encerra hoje: vermelho)

---

Tema Atenas:

Página Inicial
- Elementos centralizados deixando muito espaço em branco nas laterais
- Texto centralizado dentro da pauta também perde espaço nas laterais
- Colocar botão ou link específico para o arquivo que foi subido (está em formato texto, pouco amigável e sem link)
- Botão "saiba porque participar" em outra cor com mais destaque
- Filtros desalinhados e com diferentes fontes
- Sugestão de ajuste do filtro para que não precise clicar no botão recarregar a cada filtragem
- Sugestão de utilização do grid para ajuste do responsivo e melhor alinhamento dos elementos

Página da Pauta
- Espaço lateral pouco utilizado
- Melhorar visualização das opções da pauta (imprimir, discutir, seguir)
- Alinhar melhor texto da pauta e botões de compartilhamento
- Elementos "saindo da tela" nas resoluções menores
- Elementos colados na lateral na resoluções abaixo de 910px
- Melhorar apresentação da discussão
