### ISSUE TITLE
Menu no Wordpress 3.8.1

### ISSUE THREAD

**Issue by jacsonp** [redelivre/delibera#41]
_From @berlotto on April 3, 2014 13:37_

Ao clicar para adicionar o menu do Delibera no menu do site, utilizando o wordpress 3.8.1, com tema "Twenty Twelve" ocorre o erro:

ReferenceError: delibera_addMenuItemToBottom_processMethod is not defined

_Copied from original issue: ethymos/delibera#28_

**Comment by jacsonp** [comment]
_From @berlotto on April 3, 2014 15:33_

Este problema está sendo causado por que a variavel WP_CONTENT_URL não está retornando "https://" ao invés de "http://" quando a configuração "FORCE_SSL_ADMIN" está ativa.
Assim, não está carregando nenhum dos scripts e css's na área de administração do site.

**Comment by jpmehl** [comment]
@jacsonp acho que já ultrapassamos esta versão faz tempo, né? bora fechar a issue
