### ISSUE TITLE
Problemas na etapa relatoria

### ISSUE THREAD

**Issue by jacsonp** [redelivre/delibera#43]
_From @stamato on June 2, 2014 22:57_

Quando estamos em relatoria, no tema creta, nao se consegue forcar o fim do prazo para o periodo de relatoria. 

No tema atenas se consegue forcar, mas todas as propostas vao para votacao, nao permitindo ao adm selecionar as que irao ser votadas. Existem as checkbox onde se escolhe quais serao votadas, mas nao existe um botao que salva essas configuracoes e o sistema leva todas pra votacao.

_Copied from original issue: ethymos/delibera#30_

**Comment by jpmehl** [comment]
@jacsonp @lpirola acho que já temos outra issue que trata disto, bora fechar esta?
