### ISSUE TITLE
Upload de arquivos na criação de pautas

### ISSUE THREAD

**Issue by jacsonp** [redelivre/delibera#46]
_From @marcoamarelo on March 26, 2015 15:8_

O delibera precisa suportar o upload de arquivos na criação de pautas, pois essa também é uma forma dos colaboradores contribuirem para o debate.

_Copied from original issue: ethymos/delibera#38_

**Comment by jacsonp** [comment]
_From @jpmehl on March 26, 2015 19:12_

Esta funcionalidade existia originalmente no comentário, onde o usuário
poderia inserir um arquivo no seu comentário, mas foi descontinuada por ser
um plugin externo ao delibera.
Também é possível que ele faça upload ao criar a proposta no backend.
Então acho que poderia ser pensada uma solução que permitisse uploads tanto
na criação de pauta no frontend quanto nos comentário.

Em 26 de março de 2015 12:08, marcoamarelo notifications@github.com
escreveu:

> O delibera precisa suportar o upload de arquivos na criação de pautas,
> pois essa também é uma forma dos colaboradores contribuirem para o debate.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ethymos/delibera/issues/38.

## 

João Paulo Mehl
Ethymos Soluções em Web
www.ethymos.com.br
(41)3077-4163 / 9627-5518

**Comment by jacsonp** [comment]
_From @marcoamarelo on March 26, 2015 23:34_

Let's do it ;-)

**Comment by lpirola** [comment]
@jacsonp podemos aplicar a mesma abordagem do upload de documentos nos comentários #18 O que acha?

**Comment by lpirola** [comment]
#18 Resolvemos com abordagem mais  ampla e incluímos player para video e audio.
