### ISSUE TITLE
Melhorar a usabilidade de botão de retorno à capa

### ISSUE THREAD

**Issue by jacsonp** [redelivre/delibera#48]
_From @anapaulabrasa on November 4, 2015 15:34_

Melhorar a usabilidade e a visualidade de botão "VOLTAR A PÁGINA DE DISCUSSÕES" (nas internas das pautas). Tema Atenas.

_Copied from original issue: ethymos/delibera#47_

**Comment by jpmehl** [comment]
@diegorojas da uma olhada nisto pra fecharmos esta issue

**Comment by diegorojas** [comment]
Alguem me ajuda a visualizar isso aqui? Podem colar um print no comentário, num to conseguindo localizar

**Comment by jacsonp** [comment]
Não sei se é isso:
![captura de tela de 2016-04-05 18 38 19](https://cloud.githubusercontent.com/assets/3977652/14298857/9e99cfbc-fb5d-11e5-8f2d-79f44da7a210.png)

**Comment by jacsonp** [comment]
Se houve confusão com o tema generic, a imagem seria essa:
![captura de tela de 2016-04-05 18 45 22](https://cloud.githubusercontent.com/assets/3977652/14299038/a26e6cb4-fb5e-11e5-8209-72997833d799.png)

**Comment by diegorojas** [comment]
Entendi, mas achei que tinha resolvido isso ai no header mesmo não? Ta no ar:
![voltar-as-pautas](https://cloud.githubusercontent.com/assets/3632627/14299043/a7628c32-fb5e-11e5-8784-f8b5a59ecded.png)

**Comment by jacsonp** [comment]
Não sei, o @jpmehl vai ter que responder essa!

**Comment by diegorojas** [comment]
Acho que se for para melhorar isso ai a transparência do botão tá ruim, pode ser sólida como o saiba mais

**Comment by diegorojas** [comment]
Isso foi feita em minha primeira revisão, não fiz referência :(

**Comment by diegorojas** [comment]
Para mim isso resolveu, certo?
