### ISSUE TITLE
Possibilitar citar usuários quando estiver criando comentário, abrir popup de lista de usuários

### ISSUE THREAD

**Issue by jacsonp** [redelivre/delibera#54]
ref #34

**Comment by jacsonp** [comment]
Plugin para referência:
https://wordpress.org/support/view/plugin-reviews/mention-comments-authors

**Comment by jacsonp** [comment]
Vamos somente de comentário

**Comment by lpirola** [comment]
Realizei testes utilizando o plugin creta do delibera. Como vamos repensar essa parte de temas dentro do delibera, não estou testando o tema atenas, só o creta é testado mais exaustivamente.
