### ISSUE TITLE
Integrar delibera com plugin criado ou escolhido para mentions

### ISSUE THREAD

**Issue by lpirola** [redelivre/delibera#58]

**Comment by jpmehl** [comment]
Esta issue é para atender a demanda de citar participantes, certo? Avaliando aqui, a gente teria que ter um ambiente de notificações no delibera, onde o cara pudesse ver um fluxo dos debates em que ele está envolvido com os respectivos prazos e as citações que ele teve...

**Comment by lpirola** [comment]
#54 ajuda a resolver essa questão, irei pegá-las para poder dar início a utilização dessa funcionalidade.

**Comment by lpirola** [comment]
![user-mentions](https://cloud.githubusercontent.com/assets/14948/13762915/196cb248-ea21-11e5-936c-5547ae60f45a.gif)
