### ISSUE TITLE
Possibilitar listar informações referentes ao delibera na página dedicada ao usuário

### ISSUE THREAD

**Issue by lpirola** [redelivre/delibera#59]
Criar funções no php que possibilite aos criadores de tema listar as informações criadas pelo plugin do delibera.

**Comment by cabelotaina** [comment]
@lpirola @jacsonp @jpmehl essas infos? 

![screenshot from 2016-03-07 11 22 20](https://cloud.githubusercontent.com/assets/1827173/13572036/e1de5df6-e456-11e5-8bb6-967d83125a06.png)

**Comment by lpirola** [comment]
@cabelotaina creio que sim a princípio mas é importante tomar cuidado com o PR #66 do @jacsonp q muda muita coisa no fluxo e nos módulos que podem estar ativo ou não.

**Comment by lpirola** [comment]
Na verdade, acho que não tem muito a ver essas notificações nessa issue. Aqui é mais para construir interfaces no php (function) para possibilitar no tema carregas as infos, sacou?

**Comment by jacsonp** [comment]
Não, acho q é nesse local, mas infos sobre participação, comentários, etc...

**Comment by cabelotaina** [comment]
@jacsonp @lpirola mas ai fica sem sentido temos apenas que fazer a issue #60 de maneira que os comentário passem por um parser, assim sabemos qual foi a decisão de um usuário sobre uma determinada pauta. E não apenas apresentar os comentários como esta na #60 e sim filtrar eles como processos:

Maurilio 
- criou a proposta de pauta Musica nas Escolas a 3 minutos
- propos o encaminhamento: oficionas de EAD para a Pauta desenvolvimento de software no Vale do Ribeira a 7 minutos
- votou na Pauta desenvolvimento de software no Vale do Ribeira a 10 minutos

É isso?

**Comment by jacsonp** [comment]
a #60 é a capacidade de gerar listagens e filtros e nessa é o histórico do que o usuário fez, basicamente a sua proposta, entende? E como o @lpirola falou, é mais uma interface, mas é sempre bom ter exemplos em funcionamento.

**Comment by jpmehl** [comment]
Podem me dar algum exemplo, to achando que confundi a issu #55 com esta.
