### ISSUE TITLE
Possibilidade de listar comentários ou posts por usuários

### ISSUE THREAD

**Issue by lpirola** [redelivre/delibera#60]
Documentação de como implementar no tema do wordpress essa demanda.

**Comment by jpmehl** [comment]
O objetivo desta demanda é permitir um maior controle social sobre as interações dos participantes, assim é possível visualizarmos que tipo de informação o usuário insere na plataforma e quais debates ele interage. 
Vejo que temos que prever uma página específica do usuário, onde estar informações estariam apresentadas. 
Acho que no culturadigital.br, que utiliza o buddypress tem coisas interessantes.

**Comment by jpmehl** [comment]
Clicando no meu usuários, ele só me apresentou os posts que eu publiquei, nenhuma informação relativa ao delibera, ver em: http://novocnpc.beta.redelivre.org.br/author/jpmehl/

**Comment by jacsonp** [comment]
Acredito que precisamos atualizar o links no template né @cabelotaina ?

**Comment by jpmehl** [comment]
@lpirola @jacsonp @cabelotaina Esta issue tem relação com pelo menos outras duas que dizem respeito a filtragem de conteúdo por usuário, vi que ela está em review, mas nos testes que fiz ela não apareceu. Isto é o PR que está agurdando aprovação https://github.com/redelivre/delibera/pull/121?

**Comment by cabelotaina** [comment]
@jpmehl sim é ela mesmo. Existe duas resalvas que coloquei, acredito que @jacsonp seja a pessoa ideia para fazer a revisão já que ele faz a revisão do primeiro pr que eu fiz para esta issue.

**Comment by jpmehl** [comment]
Acho que precisamos de um papo pra escarecer as issues #55 #59 e #60
