### ISSUE TITLE
Melhorar usabilidade do sistema de fluxo

### ISSUE THREAD

**Issue by jacsonp** [redelivre/delibera#68]
Usar telas do desafio da @thalitasejanes como base seria interessante

**Comment by jpmehl** [comment]
Ficou muito melhor a tela! Percebi apenas que na coluna da esquerda a ordem do fluxo está errada( pauta em discussão, relatoria, resolução, proposta de pauta, regime de votação). Eu corrigi, salvei, mas não salvou efetivamente. 
Na da direita, estava sem o "proposta de pauta" eu incluí e funcionou.

**Comment by jpmehl** [comment]
Mas reparei que a tela na pauta em si não mudou, certo?
