### ISSUE TITLE
Voto para proposta de encaminhamento vazioAo ler um post ou comentário, relacionar o perfil do citado na texto

### ISSUE THREAD

**Issue by cabelotaina** [redelivre/delibera#77]
Quando um usuário tenta realizar um voto o servidor dispara uma mensagem "selecione ao menos uma opção de voto". Ainda que uma opção esteja selecionada.

A issue #60 e a issue #59 dependem desta funcionalidade. 

Aparentemente as informações que devem ser renderizadas dentro do formulario de voto em proposta de encaminhamento estão sendo renderizadas dentro do formulário de anexo de arquivos. 
Tentei corrigir o erro no entanto não consegui entender o funcionamento do formulário de anexo de arquivos.

**Comment by lpirola** [comment]
Você está usando qual tema do Delibera?

**Comment by cabelotaina** [comment]
![screenshot from 2016-03-15 15 50 34](https://cloud.githubusercontent.com/assets/1827173/13790209/1043fffa-eac6-11e5-90e9-a208f907b29e.png)
