### ISSUE TITLE
Regime de votação não permite o voto

### ISSUE THREAD

**Issue by jpmehl** [redelivre/delibera#81]
Fiz um primeiro teste após a implementação dos módulos. deu tudo certo a escolha dos módulos, só na hora de votar que dá a seguinte mensagem"Você precisa selecionar pelo menos um encaminhamento." Sendo que eu estava selecionando. 
Da pra ver o erro aqui: http://novocnpc.beta.redelivre.org.br/pauta/teste-de-pauta-com-novo-fluxo/

**Comment by jacsonp** [comment]
#77
