### ISSUE TITLE
Pauta direto para regime de votação

### ISSUE THREAD

**Issue by jpmehl** [redelivre/delibera#82]
Quando a pauta for direto para o regime de votação ela deve permitir que o administrador insira quais são as propostas que serão colocadas em votação.

**Comment by jacsonp** [comment]
já implementado, precisa melhor UX possivelmente.
![captura de tela de 2016-03-24 11 57 28](https://cloud.githubusercontent.com/assets/3977652/14020851/b1c2fad2-f1b7-11e5-9d87-7cc9c965cc20.png)
