### ISSUE TITLE
Bug com nível de comentários ao cadastrar novo comentário

### ISSUE THREAD

**Issue by lpirola** [redelivre/delibera#86]
Estava lendo os comentários dessa discussão no  novo cpnc e verifiquei que o bug ocorre mesmo. Consegue checar isso?

O link para discussão: http://novocnpc.beta.redelivre.org.br/pauta/sobre-esta-plataforma-de-testes/#delibera-comments

Esse bug faz referência ao #16?

**Comment by jacsonp** [comment]
Quando eu clico no botão responder, o form não está pegando o id do comentários como deveria através da função addComment.moveForm( "div-comment-xx", "xx", "respond", "xxxxx" )

**Comment by lpirola** [comment]
Achei que utilizasse o mecanismo do próprio Divi. Consegue me ajudar a ver isso amanhã?

**Comment by jacsonp** [comment]
já to resolvendo
