### ISSUE TITLE
Botão seguir não funciona no ambiente do beta

### ISSUE THREAD

**Issue by lpirola** [redelivre/delibera#87]
No beta, a requisição ajax que é disparada ao clicar no botão seguir do tema "genérico" retorna "-1". consegue testar se isso funciona para você também e se tem o mesmo retorno?

O certo seria retornar "1".

**Comment by jacsonp** [comment]
para mim está funcionando tanto no beta quanto localmente

**Comment by lpirola** [comment]
O @jpmehl reportou esse bug tb. Qual pauta vc seguiu?

**Comment by jacsonp** [comment]
http://novocnpc.beta.redelivre.org.br/pauta/sobre-esta-plataforma-de-testes

**Comment by jacsonp** [comment]
![captura de tela de 2016-03-29 03 13 22](https://cloud.githubusercontent.com/assets/3977652/14099486/3f9b17b6-f55c-11e5-9025-a9264dc0e5e3.png)

**Comment by jacsonp** [comment]
Mas alguém viu esse problema? Favor informar url, navegador e SO
