### ISSUE TITLE
Estilo área de comentários e interações.

### ISSUE THREAD

**Issue by jpmehl** [redelivre/delibera#90]
Os botões de Concordar e discordar deve ser apenas um V para concordar e um X para discordar conforme projeto gráfico proposto.

**Comment by jpmehl** [comment]
Conforme já coloquei em reunião, mas sistematizo aqui, ampliando esta issue para as formas de intaração: 

NÍVEL EDIÇÃO
1) Os botões "editar" e "deletar" não deveriam aparecer tal qual eles estão, acho que poderíamos ter no canto superior direto uma "gravata" que quando o usuário clicasse abrisse as opcṍes de "editar" e "deletar, justifico isto pois acho que esta implementação será útil para futuras novas formas de interação. 

NÍVEL DE INTERAÇÃO 1 ( no comentário de uma pessoa) 
1) Vejo que as possibilidades de interação devem estar todas juntas: a) Responda b) Concordar c) discordar 

NÍVEL DE INTERAÇÃO 2 (ao comentar a pauta ou outro comentário) 
1) Vejo que ao clicar no "responder) deve
a) abrir logo abaixo uma caixa de comentário
b) o título da páuta é desnecessário, deve cair. 
c) o "cancelar a resposta" deve estar abaixo, junto com as outras interaçõe, e deve ser somente "cancelar"
d) acima da caixa deve ficar apenas a seleção para: a) opinião b) proposta (excluir o "de encaminhamento")
e) Abaixo do box de comentário devem estar aglutinados: 1) publicar(excluir o "comentário) 2) botão para anexar 3) cancelar
f) Por último, a título de comentário geral, acho que esta área precisa ser mais orgânica, as coisa precisam estar bem enxutas e encaixadas, acho que a caixa de comentário pode ser mais larga e mais fina e os botões mais integrados. Enfim, já falei anteriormente que esta é das áreas que sou mais insatisfeito.

**Comment by diegorojas** [comment]
Estou melhorando progressivamente aqui, mas não consigo reordenar no código, aqui esta onde cheguei:

![tela-comentario-agora](https://cloud.githubusercontent.com/assets/3632627/14868338/77f0f4c4-0ca3-11e6-8f04-4b1c72e8bef6.png)

Segue abaixo o desenho de como o joão está visualizando e desenhei:

![tela-comentario-futuro](https://cloud.githubusercontent.com/assets/3632627/14868355/8c8af484-0ca3-11e6-9473-f2e5b32775cd.png)

Podem me ajudar @jacsonp e @lpirola ? Na sequência da reorganização acredito que podemos seguir para fazer o toogle que o JP sugeriu.

**Comment by jpmehl** [comment]
Só um comentário que já está em outra issue, eu acho, que são os botões de concordar e discordar, que devem estar junto com os oturos comando, alinhado à esquerda

**Comment by diegorojas** [comment]
Ei jacson, valeu! Veja como estamos agora... 

![agora-esta-assim](https://cloud.githubusercontent.com/assets/3632627/14896368/c512795c-0d53-11e6-8031-f6d34f1e6f7c.png)

Precisava colocar o "basear-se nesta proposta?"  ao lado de "Proposta de encaminhamento", rola?

**Comment by diegorojas** [comment]
Registrando visualmente como ficou a interação dessa área para editar um encaminhamento ou uma proposta. 

![delibera-issue90](https://cloud.githubusercontent.com/assets/3632627/19656848/69937ab0-9a00-11e6-9dc8-9961007434e5.jpg)
