### ISSUE TITLE
Relatoria - estilo mesclar propostas

### ISSUE THREAD

**Issue by jpmehl** [redelivre/delibera#93]
O estilo no nome(usuário de origem) das propostas mescladas deve ficar arrumado;

**Comment by lpirola** [comment]
@diegorojas me ajuda por favor!

**Comment by jacsonp** [comment]
http://novocnpc.beta.redelivre.org.br/pauta/pauta-pra-mostrar-a-relatoria/
![captura de tela de 2016-04-05 15 58 22](https://cloud.githubusercontent.com/assets/3977652/14294423/6acb7296-fb47-11e5-878e-f942abc9bf11.png)

**Comment by jacsonp** [comment]
observar que o encaminhamento gerado também está estranho:
![captura de tela de 2016-04-14 10 58 15](https://cloud.githubusercontent.com/assets/3977652/14530626/2d5bec7a-0230-11e6-9e4f-c7f172f55433.png)

**Comment by jpmehl** [comment]
@diegorojas esta issue está em review, no entanto, não consegui encontrar qualquer implementação.

**Comment by diegorojas** [comment]
Aqui temos o seguinte, preciso de ajuda @jacsonp para reordenar o codigo. Consegui deixar via css no máximo assim:
![estilo-mesclar-propostas](https://cloud.githubusercontent.com/assets/3632627/14863926/1b7188a4-0c8e-11e6-9052-3aef819be4f4.png)

Não consegui de jeito nenhum deixar tudo concatenado na mesma linha: 
"Proposta baseada em:  @nomedeusuario, @nomedeusuario2" Precisa re-organizar o codigo, mas não consegui, poderia me ajudar?

Abaixo também me aparece um botão "form-submit", consegue verificar porque? e o retirar se possivel? não consegui retirar via css sem afetar outros trechos.

**Comment by jacsonp** [comment]
vou ver agora

**Comment by jpmehl** [comment]
No texto, colocar:

Proposta(acho que trocamos encaminhamento por proposta por ser mais
intuitivo)

Baseado nas propostas de: @fulano, @beltrano, @ciclano
Em 27 de abr de 2016 10:13 PM, "Jacson" notifications@github.com escreveu:

**Comment by jpmehl** [comment]
Gente, fazendo os testes de relatoria de pauta eu percebi que ele junta as propsotas que eu sistematizei(mas não mostra as propostas originais aglutinadas), e mostra as propostas originais separadas, como se não tivessem sido sistematizadas, criando mais opções que deveriam ter. Podem visualizar isto nesta pauta: http://escoladedebate.redecnpc.redelivre.org.br/pauta/teste-de-fluxo-completo-jp-e-thalita/#delibera-comment-

Tb tirei um print pra verem que está encavalando geral: 

![print](https://cloud.githubusercontent.com/assets/4163139/19248644/bb121346-8f07-11e6-96c3-89f2855f3b5d.png)

**Comment by jacsonp** [comment]
fiquei em uma dúvida aqui, no meu entendimento, o relator vai ter que repetir o texto em sua proposta, mas quando fala em juntar, me gerou uma dúvida: Eu coloco apenas um link para mostrar a original ou tenho que juntar os texto?

**Comment by diegorojas** [comment]
Registrando o estilo atual, mas ainda faltando uma revisão do mobile.

![image](https://cloud.githubusercontent.com/assets/3632627/19656926/bd38f97e-9a00-11e6-8644-045ee5552c07.png)
