### ISSUE TITLE
Estilo: Estágio Votação

### ISSUE THREAD

**Issue by jpmehl** [redelivre/delibera#99]
O estilo na fase votação está quebrado no que tange o descritivo da pauta(ver print) e a parte de votação precisa ser melhor resolvida esteticamente. 
![votacao-pauta-delibera](https://cloud.githubusercontent.com/assets/4163139/14270313/56bdde94-fac3-11e5-91a6-f9d34ae5ea3f.png)

**Comment by lpirola** [comment]
@diegorojas pode melhorar esse layout?

**Comment by diegorojas** [comment]
Posso sim, isso vou direto em css. Mas sobre os icones sociais tinhamos conversado de pegar o css do jetpack lembra?

![links-redes-sociais](https://cloud.githubusercontent.com/assets/3632627/14298352/ec09270a-fb5a-11e5-8861-efe6236a28c6.png)

Isso ai sairia para ficar algo assim:

![jetpack-share](https://cloud.githubusercontent.com/assets/3632627/14298377/0beeaf54-fb5b-11e5-8d14-52c7233759b7.png)

**Comment by lpirola** [comment]
Consegue fazer essa mudança? Porque como estou usando os plugins padrão de cada rede social, não consegui trocar o estilo.

**Comment by diegorojas** [comment]
Entendi, vou tentar sim, se vc não conseguiu... jesus o que me espera! :)

**Comment by diegorojas** [comment]
@lpirola por favor, onde consigo mexer na estrututa de divs do form aqui? 

![estrutura-de-divs](https://cloud.githubusercontent.com/assets/3632627/14395980/58744878-fdab-11e5-9c7d-cac917a4cbfd.png)

Não consigo resolver só com css, preciso de uma div encapsulando tudo

**Comment by lpirola** [comment]
Eu tb não tenho certeza onde isso está, trabalhei só até o comentário. Com a modularização do delibera o @jacson é a melhor pessoa para responder isso.

**Comment by jacsonp** [comment]
https://github.com/redelivre/delibera/blob/generic-theme/themes/generic/functions.php
linha 241 tem os checkboxes

**Comment by diegorojas** [comment]
@jpmehl da uma olhada e veja se esta fechado essa?

**Comment by jpmehl** [comment]
@diegorojas só resolveu a questão do descritivo da pauta, o estilo dos Checkbox pro cara poder votar estão muito ruins ainda. 

Mas já percebi que deu algum bug. Reparem que [nesta pauta ](http://novocnpc.beta.redelivre.org.br/pauta/pauta-em-votacao-direto-pra-dar-uma-testada/) eu coloquei uns 5 ou 6 comentários, mas só estão aparecendo 2, e um do lado do outro, e também apareceu a caixa para anexar arquivo, que não faz nenhum sentido. 

Também acho que não faz sentido ter a frase abaixo do descritivo: "Regime de votação para a pauta "Pauta em votação direto pra dar uma testada" já que temos a área lá em cima que já indica em que fase está. Deve estar apenas o recado em substituição a este: "Escolha os encaminhamentos que deseja aprovar e depois clique em "Votar": " Faça sua escolha e clique em VOTAR"

![pauta-votacao-bugada](https://cloud.githubusercontent.com/assets/4163139/14721258/e59d7780-07db-11e6-95e7-f1103fef4c92.png)

**Comment by diegorojas** [comment]
Jp,
Eu tinha melhorado as opções, deixados ao menos uma em cada linha, espaçados, alinhados, aconteceu alguma coisa aqui nas revisões e merges de css, desculpe não rever antes. Acho que fiz o básico agora. Acredita em fontes maiores?

Sobre o erro que relatou... Acredito que precise dos universitarios @jacson. Novidade aqui é que está aparecendo um elemento que não me aparecia antes na interface... Ele fica oculta invisível pois está sem conteúdo mas fica la, antes do final da .content

<div class="warning message">
</div>

**Comment by diegorojas** [comment]
Manos,

Alguém consegue fazer isso aqui abaixo no front-end?

![upload-para-front-end](https://cloud.githubusercontent.com/assets/3632627/14895747/97132fb8-0d50-11e6-83c1-d3a1b1444b01.png)

**Comment by lpirola** [comment]
Acho que não conseguimos. O ideia é estilizar apenas o input file através do css. Como aqui: http://tympanus.net/codrops/2015/09/15/styling-customizing-file-inputs-smart-way/

**Comment by diegorojas** [comment]
Legal pessoal, Então acho que temos que ir por aqui:

![publicar-com-anexar](https://cloud.githubusercontent.com/assets/3632627/14903448/7d047e84-0d77-11e6-9c90-d6d185b5b143.jpg)

Agora @jacsonp quando for uma publicação em resposta a outra, acho que precisa somar o botão cancelar então antes do anexar:

![publicar-com-cancelar-e-anexar](https://cloud.githubusercontent.com/assets/3632627/14903504/ed455146-0d77-11e6-95d5-82826b66355a.jpg)

Acho que assim, chegaremos numa UX beeem mais legal hein... :)

**Comment by diegorojas** [comment]
O estilo dessa area foi revisto e está conforme a tela abaixo:
![image](https://cloud.githubusercontent.com/assets/3632627/19656996/01e69694-9a01-11e6-9aac-e588df0cf273.png)
